export const CREATE_CUSTOMER_REQUEST = "CREATE_CUSTOMER_REQUEST";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const CREATE_CUSTOMER_FAIL = "CREATE_CUSTOMER_FAIL";

export const NEW_CUSTOMER_RESET = "NEW_CUSTOMER_RESET";

export const CUSTOMER_DETAILS_SUCCESS = "CUSTOMER_DETAILS_SUCCESS";
export const CUSTOMER_DETAILS_REQUEST = "CUSTOMER_DETAILS_REQUEST";
export const CUSTOMER_DETAILS_FAIL = "CUSTOMER_DETAILS_FAIL";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";

export const USER_CUSTOMER_DETAILS_SUCCESS = "USER_CUSTOMER_DETAILS_SUCCESS";
export const USER_CUSTOMER_DETAILS_REQUEST = "USER_CUSTOMER_DETAILS_REQUEST";
export const USER_CUSTOMER_DETAILS_FAIL = "USER_CUSTOMER_DETAILS_FAIL";
export const CUSTOMER_DETAILS_RESET = "CUSTOMER_DETAILS_RESET";

export const UPDATE_CUSTOMER_FAIL = "UPDATE_CUSTOMER_FAIL";
export const UPDATE_CUSTOMER_REQUEST = "UPDATE_CUSTOMER_REQUEST";
export const UPDATE_CUSTOMER_RESET = "UPDATE_CUSTOMER_RESET";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";

export const UPDATE_CUSTOMER_STATUS_FAIL = "UPDATE_CUSTOMER_STATUS_FAIL";
export const UPDATE_CUSTOMER_STATUS_REQUEST = "UPDATE_CUSTOMER_STATUS_REQUEST";
export const UPDATE_CUSTOMER_STATUS_RESET = "UPDATE_CUSTOMER_STATUS_RESET";
export const UPDATE_CUSTOMER_STATUS_SUCCESS = "UPDATE_CUSTOMER_STATUS_SUCCESS";

export const UPDATE_CUSTOMER_PASSWORD_FAIL = "UPDATE_CUSTOMER_PASSWORD_FAIL";
export const UPDATE_CUSTOMER_PASSWORD_REQUEST =
  "UPDATE_CUSTOMER_PASSWORD_REQUEST";
export const UPDATE_CUSTOMER_PASSWORD_RESET = "UPDATE_CUSTOMER_PASSWORD_RESET";
export const UPDATE_CUSTOMER_PASSWORD_SUCCESS =
  "UPDATE_CUSTOMER_PASSWORD_SUCCESS";

export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";
export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_RESET = "DELETE_CUSTOMER_RESET";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";

export const ALL_CUSTOMER_REQUEST = "ALL_CUSTOMER_REQUEST";
export const ALL_CUSTOMER_SUCCESS = "ALL_CUSTOMER_SUCCESS";
export const ALL_CUSTOMER_FAIL = "ALL_CUSTOMER_FAIL";
export const ALL_CUSTOMER_UPDATE = "ALL_CUSTOMER_UPDATE";

export const ALL_CUSTOMER_NAME_REQUEST = "ALL_CUSTOMER_NAME_REQUEST";
export const ALL_CUSTOMER_NAME_SUCCESS = "ALL_CUSTOMER_NAME_SUCCESS";
export const ALL_CUSTOMER_NAME_FAIL = "ALL_CUSTOMER_NAME_FAIL";

export const ALL_CUSTOMER_PARTY_REQUEST = "ALL_CUSTOMER_PARTY_REQUEST";
export const ALL_CUSTOMER_PARTY_SUCCESS = "ALL_CUSTOMER_PARTY_SUCCESS";
export const ALL_CUSTOMER_PARTY_FAIL = "ALL_CUSTOMER_PARTY_FAIL";

export const ALL_CUSTOMER_PARTY_ID_REQUEST = "ALL_CUSTOMER_PARTY_ID_REQUEST";
export const ALL_CUSTOMER_PARTY_ID_SUCCESS = "ALL_CUSTOMER_PARTY_ID_SUCCESS";
export const ALL_CUSTOMER_PARTY_ID_FAIL = "ALL_CUSTOMER_PARTY_ID_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
