export const CREATE_DIGITAL_REQUEST = "CREATE_DIGITAL_REQUEST";
export const CREATE_DIGITAL_SUCCESS = "CREATE_DIGITAL_SUCCESS";
export const CREATE_DIGITAL_FAIL = "CREATE_DIGITAL_FAIL";

export const NEW_DIGITAL_RESET = "NEW_DIGITAL_RESET";
export const DELETE_DIGITAL_RESET = "DEELTE_DIGITAL_RESET";

export const UPDATE_DIGITAL_FAIL = "UPDATE_DIGITAL_FAIL";
export const UPDATE_DIGITAL_REQUEST = "UPDATE_DIGITAL_REQUEST";
export const UPDATE_DIGITAL_RESET = "UPDATE_DIGITAL_RESET";
export const UPDATE_DIGITAL_SUCCESS = "UPDATE_DIGITAL_SUCCESS";

export const DELETE_DIGITAL_FAIL = "DELETE_DIGITAL_FAIL";
export const DELETE_DIGITAL_REQUEST = "DELETE_DIGITAL_REQUEST";
export const DELETE_DIGITAL_SUCCESS = "DELETE_DIGITAL_SUCCESS";

export const ALL_DIGITAL_REQUEST = "ALL_DIGITAL_REQUEST";
export const ALL_DIGITAL_SUCCESS = "ALL_DIGITAL_SUCCESS";
export const ALL_DIGITAL_FAIL = "ALL_DIGITAL_FAIL";

export const ALL_CUSTOMER_NAME_REQUEST = "ALL_CUSTOMER_NAME_REQUEST";
export const ALL_CUSTOMER_NAME_SUCCESS = "ALL_CUSTOMER_NAME_SUCCESS";
export const ALL_CUSTOMER_NAME_FAIL = "ALL_CUSTOMER_NAME_FAIL";

export const DIGITAL_DETAILS_SUCCESS = "DIGITAL_DETAILS_SUCCESS";
export const DIGITAL_DETAILS_REQUEST = "DIGITAL_DETAILS_REQUEST";
export const DIGITAL_DETAILS_FAIL = "DIGITAL_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
