export const CREATE_INTERNAL_ORDER_REQUEST = "CREATE_INTERNAL_ORDER_REQUEST";
export const CREATE_INTERNAL_ORDER_SUCCESS = "CREATE_INTERNAL_ORDER_SUCCESS";
export const CREAT_INTERNAL_ORDER_FAIL = "CREAT_INTERNAL_ORDER_FAIL";

export const NEW_INTERNAL_ORDER_RESET = "NEW_INTERNAL_ORDER_RESET";

export const INTERNAL_ORDER_DETAILS_SUCCESS = "INTERNAL_ORDER_DETAILS_SUCCESS";
export const INTERNAL_ORDER_DETAILS_REQUEST = "INTERNAL_ORDER_DETAILS_REQUEST";
export const INTERNAL_ORDER_DETAILS_FAIL = "INTERNAL_ORDER_DETAILS_FAIL";

export const UPDATE_INTERNAL_ORDER_FAIL = "UPDATE_INTERNAL_ORDER_FAIL";
export const UPDATE_INTERNAL_ORDER_REQUEST = "UPDATE_INTERNAL_ORDER_REQUEST";
export const UPDATE_INTERNAL_ORDER_RESET = "UPDATE_INTERNAL_ORDER_RESET";
export const UPDATE_INTERNAL_ORDER_SUCCESS = "UPDATE_INTERNAL_ORDER_SUCCESS";

export const DELETE_CUSTOMER_FAIL = "DELETE_CUSTOMER_FAIL";
export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_RESET = "DELETE_CUSTOMER_RESET";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";

export const ALL_CUSTOMER_REQUEST = "ALL_CUSTOMER_REQUEST";
export const ALL_CUSTOMER_SUCCESS = "ALL_CUSTOMER_SUCCESS";
export const ALL_CUSTOMER_FAIL = "ALL_CUSTOMER_FAIL";

export const ALL_CUSTOMER_NAME_REQUEST = "ALL_CUSTOMER_NAME_REQUEST";
export const ALL_CUSTOMER_NAME_SUCCESS = "ALL_CUSTOMER_NAME_SUCCESS";
export const ALL_CUSTOMER_NAME_FAIL = "ALL_CUSTOMER_NAME_FAIL";

export const ALL_CUSTOMER_PARTY_REQUEST = "ALL_CUSTOMER_PARTY_REQUEST";
export const ALL_CUSTOMER_PARTY_SUCCESS = "ALL_CUSTOMER_PARTY_SUCCESS";
export const ALL_CUSTOMER_PARTY_FAIL = "ALL_CUSTOMER_PARTY_FAIL";

export const ALL_CUSTOMER_PARTY_ID_REQUEST = "ALL_CUSTOMER_PARTY_ID_REQUEST";
export const ALL_CUSTOMER_PARTY_ID_SUCCESS = "ALL_CUSTOMER_PARTY_ID_SUCCESS";
export const ALL_CUSTOMER_PARTY_ID_FAIL = "ALL_CUSTOMER_PARTY_ID_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
