export const CREATE_INTERNAL_PARTY_REQUEST = "CREATE_INTERNAL_PARTY_REQUEST";
export const CREATE_INTERNAL_PARTY_SUCCESS = "CREATE_INTERNAL_PARTY_SUCCESS";
export const CREATE_INTERNAL_PARTY_FAIL = "CREATE_INTERNAL_PARTY_FAIL";

export const NEW_INTERNAL_PARTY_RESET = "NEW_INTERNAL_PARTY_RESET";

export const INTERNAL_PARTY_DETAILS_SUCCESS = "INTERNAL_PARTY_DETAILS_SUCCESS";
export const INTERNAL_PARTY_DETAILS_REQUEST = "INTERNAL_PARTY_DETAILS_REQUEST";
export const INTERNAL_PARTY_DETAILS_FAIL = "INTERNAL_PARTY_DETAILS_FAIL";

export const UPDATE_INTERNAL_PARTY_FAIL = "UPDATE_INTERNAL_PARTY_FAIL";
export const UPDATE_INTERNAL_PARTY_REQUEST = "UPDATE_INTERNAL_PARTY_REQUEST";
export const UPDATE_INTERNAL_PARTY_RESET = "UPDATE_INTERNAL_PARTY_RESET";
export const UPDATE_INTERNAL_PARTY_SUCCESS = "UPDATE_INTERNAL_PARTY_SUCCESS";

export const DELETE_INTERNAL_PARTY_FAIL = "DELETE_INTERNAL_PARTY_FAIL";
export const DELETE_INTERNAL_PARTY_REQUEST = "DELETE_INTERNAL_PARTY_REQUEST";
export const DELETE_INTERNAL_PARTY_RESET = "DELETE_INTERNAL_PARTY_RESET";
export const DELETE_INTERNAL_PARTY_SUCCESS = "DELETE_INTERNAL_PARTY_SUCCESS";

export const ALL_INTERNAL_PARTY_REQUEST = "ALL_INTERNAL_PARTY_REQUEST";
export const ALL_INTERNAL_PARTY_SUCCESS = "ALL_INTERNAL_PARTY_SUCCESS";
export const ALL_INTERNAL_PARTY_FAIL = "ALL_INTERNAL_PARTY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
