export const CREATE_PARTY_REQUEST = "CREATE_PARTY_REQUEST";
export const CREATE_PARTY_SUCCESS = "CREATE_PARTY_SUCCESS";
export const CREATE_PARTY_FAIL = "CREATE_PARTY_FAIL";

export const NEW_PARTY_RESET = "NEW_PARTY_RESET";

export const PARTY_DETAILS_SUCCESS = "PARTY_DETAILS_SUCCESS";
export const PARTY_DETAILS_REQUEST = "PARTY_DETAILS_REQUEST";
export const PARTY_DETAILS_FAIL = "PARTY_DETAILS_FAIL";

export const UPDATE_PARTY_FAIL = "UPDATE_PARTY_FAIL";
export const UPDATE_PARTY_REQUEST = "UPDATE_PARTY_REQUEST";
export const UPDATE_PARTY_RESET = "UPDATE_PARTY_RESET";
export const UPDATE_PARTY_SUCCESS = "UPDATE_PARTY_SUCCESS";

export const DELETE_PARTY_FAIL = "DELETE_PARTY_FAIL";
export const DELETE_PARTY_REQUEST = "DELETE_PARTY_REQUEST";
export const DELETE_PARTY_RESET = "DELETE_PARTY_RESET";
export const DELETE_PARTY_SUCCESS = "DELETE_PARTY_SUCCESS";

export const ALL_PARTY_REQUEST = "ALL_PARTY_REQUEST";
export const ALL_PARTY_SUCCESS = "ALL_PARTY_SUCCESS";
export const ALL_PARTY_FAIL = "ALL_PARTY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
