export const ALL_TRASH_REQUEST = "ALL_TRASH_REQUEST";
export const ALL_TRASH_SUCCESS = "ALL_TRASH_SUCCESS";
export const ALL_TRASH_FAIL = "ALL_TRASH_FAIL";

export const CREATE_TRASH_REQUEST = "CREATE_TRASH_REQUEST";
export const CREATE_TRASH_FAIL = "CREATE_TRASH_FAIL";
export const CREATE_TRASH_SUCCESS = "CREATE_TRASH_SUCCESS";

export const DELETE_TRASH_REQUEST = "DELETE_TRASH_REQUEST";
export const DELETE_TRASH_FAIL = "DELETE_TRASH_FAIL";
export const DELETE_TRASH_SUCCESS = "DELETE_TRASH_SUCCESS";
export const DELETE_TRASH_RESET = "DELETE_TRASH_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
